### ISSUE TITLE
Doesn't work with threaded comments

### ISSUE THREAD

**Issue by gabrielwinnberg** [jnorell/comment-tweaks#2]
All plugins I've tried that activates TinyMCE fails with threaded comments. Got a fix for it?

**Comment by jnorell** [comment]
The issue is that when replying to a previous comment, the comment field moves (dom change) and that breaks TinyMCE - the fix is to remove the old editor, perform the dom change, then add the editor back.

The comment-tweaks plugin should handle this (I just tested again on twentynineteen theme), you can [see what it does](https://github.com/jnorell/comment-tweaks/blob/master/public/js/comment-tweaks-public.js#L188) as an example (and don't forget to handle the cancel button when canceling a reply, which also moves the comment field).
